project:
  type: book

book:
  title: "Technologie chmurowe"
  author: "Magdalena Tkacz, Bartosz Szóstak, Łukasz Wawrowski"
  date: ""
  chapters:
    - index.qmd
    - 00-organizacja.qmd
    - 01-linux.qmd
    - 02a-azure.qmd
    - 03-ci_cd.qmd
    - 04-docker.qmd
    - 05-ansible.qmd
    - 06-terraform.qmd

format:
  html:
    toc-title: "Spis treści"
    theme:
      - cosmo
      - brand
